version: "1.0"
stages:
  - clone
steps:
  clone:
      title: Cloning repository
      type: git-clone
      repo: alina-codefresh/on-prem-2.6.0
      git: github-7
      stage: clone
      revision: main
