version: "1.0"
stages:
  - clone
steps:
  clone:
      title: Cloning repository
      type: git-clone
      repo: alina-codefresh/alina-onprem-2.10
      git: github-2.10
      stage: clone
      revision: main
