version: "1.0"
stages:
  - clone
steps:
  clone:
      title: Cloning repository
      type: git-clone
      repo: alina-codefresh/on-prem-2.8.0
      git: github-2.8.0-token
      stage: clone
      revision: main
