version: "3.9"
services:
  worker:
    image: nginx
    ports:
      - "8001:80"
    networks:
      web:
  api:
    image: nginx
    ports:
      - "8002:80"
    networks:
      web:

networks:
  web:
