apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=https://hermes-onprem-test.cf-op.com/
  - cors=https://hermes-onprem-test.cf-op.com/
  - env=production
  - skipPermissionsValidation=false
  name: cap-app-proxy-cm
kind: Kustomization
namespace: onprem-test
resources:
- ../../base
